language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
script:
- npm run-script test-travis
after_success:
- eval `ssh-agent -s`
- chmod 600 .travis/deployment_id_rsa
- ssh-add .travis/deployment_id_rsa
- git remote add web ssh://dougwt@dougwt.webfactional.com:/home/dougwt/webapps/git/repos/polls.git
- echo "Pushing '$TRAVIS_BRANCH' changes to https://polls.myuserstories.com"
- git push web $TRAVIS_BRANCH --force
before_script:
- echo -e "Host dougwt.webfactional.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
before_install:
- openssl aes-256-cbc -K $encrypted_e178452e95a7_key -iv $encrypted_e178452e95a7_iv
  -in .travis/deployment_id_rsa.enc -out .travis/deployment_id_rsa -d
