export const FETCH_USER = 'FETCH_USER';

export const CREATE_POLL_RESET = 'CREATE_POLL_RESET';
export const CREATE_POLL_REQUEST = 'CREATE_POLL_REQUEST';
export const CREATE_POLL_SUCCESS = 'CREATE_POLL_SUCCESS';
export const CREATE_POLL_FAILURE = 'CREATE_POLL_FAILURE';
