export const FETCH_USER = 'FETCH_USER';

export const FETCH_POLLS = 'FETCH_POLLS';

export const SAVE_POLL_RESET = 'SAVE_POLL_RESET';
export const SAVE_POLL_REQUEST = 'SAVE_POLL_REQUEST';
export const SAVE_POLL_SUCCESS = 'SAVE_POLL_SUCCESS';
export const SAVE_POLL_FAILURE = 'SAVE_POLL_FAILURE';
